version: '3.8'
services:
    postgres:
        image: postgres:17
        environment:
            POSTGRES_DB: otp
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - "5434:5434"
